'''print("Welcome to cool school B)")
name = input("What is your name?\n")
print("Nice to meet you, " + name + "! \n" + name + " is a cool name!")'''

animal = input("Give me a animal (plural): ")
animal2 = input("Give me a different animal (plural): ")
game = input("Give me a game: ")
job = input("Give me an occupation: ")
color = input("Give me a color: ")
num = input("Give me number: ")
place = input("Give me place: ")
food = input("Give me a food (plural): ")
verb = input("Give me a verb ending in 'ing': ")
adj = input("Give me an adjective: ")
city = input("Give me a city: ")

print("Woah! Did you see the new game " + place + " " + animal2 + " " + num+ "?")
print("It's pretty much a sequel to " + game + "!")
print("It was a little " + adj + " because of how many " + color + " " + job +"s there were, but it still made me crave some " + food + "!")
print("I can't wait for the next game in the series, " + verb + " " + animal + "!" )
